### ISSUE TITLE
Error in CRA v4

### ISSUE THREAD

**Issue by sahilpurav** [GeoffSelby/cra-template-tailwindcss#9]
@GeoffSelby  With the latest version of CRA (v4), we've started getting following error:

`craco:  *** Cannot find ESLint loader (eslint-loader). ***`

Looking at the overall thread on [here](https://github.com/gsoft-inc/craco/issues/205), craco team doesn't seem to be interested in fixing it. May be we should think about switching from Craco to more native solution which is closer to CRA native method.

There is already a [pull request](https://github.com/facebook/create-react-app/pull/8907) available at CRA that allows adding postcss.config.js with the option to override the default config. Once this is launched, we should think about moving away from craco. Thoughts?

**Comment by GeoffSelby** [comment]
I will look into this some more later. I don't think the PR to add `postcss.config.js` to CRA will be merged. It's been discussed before and never happened. I'll likely try to fix craco first because I often use its other features as well so it would be nice to have. I'll update you when I know more.

**Comment by sahilpurav** [comment]
Well, in that case, you don't really need to fix anything, as soon as craco team is fixing this issue - https://github.com/gsoft-inc/craco/issues/205 You just have to update the package :) If you want you can close this issue now
